FROM apache/airflow:2.7.3-python3.11

USER root

# Install Java for Spark
RUN apt-get update && \
    apt-get install -y openjdk-11-jdk && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

USER airflow

# Install Python packages
COPY requirements-airflow.txt /tmp/
ENV PIP_NO_REQUIRE_HASHES=1
RUN pip install --no-cache-dir -r /tmp/requirements-airflow.txt

# Copy source code
COPY src/ /opt/airflow/src/

ENV PYTHONPATH="${PYTHONPATH}:/opt/airflow/src"