FROM jupyter/pyspark-notebook:latest

USER root

# Install additional packages
RUN apt-get update && apt-get install -y \
    vim \
    curl \
    && rm -rf /var/lib/apt/lists/*

USER jovyan

# Install Python packages
COPY requirements-airflow.txt /tmp/
RUN pip install --no-cache-dir -r /tmp/requirements-airflow.txt

# Set working directory
WORKDIR /home/jovyan/work